changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: 🚀 Новые функции
      labels:
        - enhancement
        - feature
    - title: 🐛 Исправления
      labels:
        - bug
        - fix
    - title: ⚡ Улучшения производительности
      labels:
        - performance
        - optimization
    - title: 📚 Документация
      labels:
        - documentation
    - title: 🔧 Обслуживание
      labels:
        - maintenance
        - dependencies
    - title: 🔒 Безопасность
      labels:
        - security
    - title: Другие изменения
      labels:
        - "*" 